// Inline Styles - Theme-aware
const light = {
  appContainer: {
    display: "flex",
    minHeight: "100vh",
    fontFamily: "Inter, system-ui, -apple-system, sans-serif",
    backgroundColor: "#F9FAFB",
    color: "#111827",
  },
  sidebar: {
    width: 240,
    backgroundColor: "#0B132B",
    color: "#9CA3AF",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "20px 16px",
    flexShrink: 0,
    height: "100%",
    minHeight: "100vh",
  },
  brandHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 28,
    justifyContent: "flex-start",
  },
  logoIcon: {
    width: 36,
    height: 36,
    backgroundColor: "transparent",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoImg: {
    width: 36,
    height: 36,
    borderRadius: "18px",
  },
  brandTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#FFFFFF",
    lineHeight: 1.2,
  },
  brandSubtitle: {
    fontSize: 10,
    color: "#6B7280",
  },
  navMenu: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 6,
    fontSize: 13.5,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  activeNavItem: {
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
  },
  sidebarFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: 11,
    color: "#4B5563",
    borderTop: "1px solid #1F2937",
    paddingTop: 16,
  },
  mainWrapper: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
  },
  topHeader: {
    height: 64,
    backgroundColor: "#FFFFFF",
    borderBottom: "1px solid #E5E7EB",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 28px",
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#111827",
    margin: 0,
  },
  breadcrumb: {
    fontSize: 12,
    fontWeight: 500,
  },
  breadcrumbLink: {
    color: "#2563EB",
    cursor: "pointer",
  },
  breadcrumbSeparator: {
    margin: "0 6px",
    color: "#9CA3AF",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  globalSearchBox: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 6,
    padding: "6px 12px",
    gap: 8,
    width: 220,
  },
  globalSearchInput: {
    border: "none",
    background: "transparent",
    outline: "none",
    fontSize: 13,
    width: "100%",
  },
  shortcutKey: {
    fontSize: 10,
    fontWeight: 600,
    color: "#9CA3AF",
    border: "1px solid #D1D5DB",
    borderRadius: 4,
    padding: "1px 4px",
    backgroundColor: "#FFFFFF",
  },
  notificationBtn: {
    position: "relative",
    padding: 6,
    cursor: "pointer",
  },
  badgeCount: {
    position: "absolute",
    top: 2,
    right: 2,
    backgroundColor: "#EF4444",
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: 700,
    borderRadius: "50%",
    width: 14,
    height: 14,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  userProfile: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    cursor: "pointer",
  },
  avatarImg: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    objectFit: "cover",
  },
  userNameText: {
    fontSize: 13,
    fontWeight: 600,
    color: "#1F2937",
  },
  userRoleText: {
    fontSize: 11,
    color: "#6B7280",
  },
  contentArea: {
    padding: 28,
    flex: 1,
  },
  alertError: {
    backgroundColor: "#FEF2F2",
    color: "#DC2626",
    border: "1px solid #FCA5A5",
    padding: "10px 14px",
    borderRadius: 6,
    fontSize: 13,
    marginBottom: 20,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E5E7EB",
    borderRadius: 8,
    padding: 16,
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  statIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  statTitle: {
    fontSize: 12,
    fontWeight: 500,
    color: "#6B7280",
  },
  statValue: {
    fontSize: 22,
    fontWeight: 700,
    color: "#111827",
    margin: "2px 0",
  },
  statBadge: {
    fontSize: 11,
    fontWeight: 600,
  },
  statSubtext: {
    fontSize: 11,
    color: "#9CA3AF",
  },
  cardContainer: {
    backgroundColor: "#FFFFFF",
    border: "1px solid #E5E7EB",
    borderRadius: 8,
    padding: 20,
  },
  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 20,
  },
  filterGroup: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    flex: 1,
  },
  tableSearchBox: {
    display: "flex",
    alignItems: "center",
    border: "1px solid #D1D5DB",
    borderRadius: 6,
    padding: "7px 12px",
    gap: 8,
    backgroundColor: "#FFFFFF",
    minWidth: 260,
  },
  tableSearchInput: {
    border: "none",
    background: "transparent",
    outline: "none",
    fontSize: 13,
    width: "100%",
  },
  selectInput: {
    border: "1px solid #D1D5DB",
    borderRadius: 6,
    padding: "7.5px 12px",
    fontSize: 13,
    backgroundColor: "#FFFFFF",
    color: "#374151",
    outline: "none",
  },
  primarySearchBtn: {
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  },
  addBtn: {
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 6,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
    fontSize: 13.5,
  },
  th: {
    padding: "12px 14px",
    color: "#6B7280",
    fontWeight: 600,
    borderBottom: "1px solid #E5E7EB",
    fontSize: 12,
  },
  tr: {
    borderBottom: "1px solid #F3F4F6",
  },
  td: {
    padding: "12px 14px",
    verticalAlign: "middle",
  },
  tableIndexText: {
    color: "#6B7280",
  },
  tableNameText: {
    fontWeight: 500,
    color: "#111827",
  },
  tableBodyText: {
    color: "#4B5563",
  },
  avatarCircle: {
    width: 30,
    height: 30,
    borderRadius: "50%",
    color: "#FFFFFF",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 700,
  },
  actionIconBtn: {
    background: "none",
    border: "1px solid #E5E7EB",
    borderRadius: 4,
    padding: 5,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmBtn: {
    backgroundColor: "#EF4444",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 4,
    padding: "3px 8px",
    fontSize: 11,
    cursor: "pointer",
  },
  cancelBtn: {
    backgroundColor: "#E5E7EB",
    color: "#374151",
    border: "none",
    borderRadius: 4,
    padding: "3px 8px",
    fontSize: 11,
    cursor: "pointer",
  },
  confirmText: {
    fontSize: 12,
    color: "#EF4444",
  },
  paginationRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
    paddingTop: 14,
    borderTop: "1px solid #F3F4F6",
  },
  pageNumberBtn: {
    border: "1px solid #E5E7EB",
    backgroundColor: "#FFFFFF",
    color: "#374151",
    borderRadius: 6,
    padding: "4px 10px",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
  },
  activePageNumber: {
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
    borderColor: "#2563EB",
  },
  pageArrowBtn: {
    border: "1px solid #E5E7EB",
    backgroundColor: "#FFFFFF",
    color: "#6B7280",
    borderRadius: 6,
    padding: "4px 8px",
    fontSize: 14,
    cursor: "pointer",
  },
  emptyState: {
    padding: 30,
    textAlign: "center",
    color: "#6B7280",
    fontSize: 14,
  },
  settingsTabHeader: {
    display: "flex",
    gap: 8,
    borderBottom: "1px solid #E5E7EB",
    paddingBottom: 12,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  settingsTabBtn: {
    background: "none",
    border: "none",
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "#6B7280",
    cursor: "pointer",
    borderRadius: 6,
  },
  settingsTabBtnActive: {
    backgroundColor: "#EFF6FF",
    color: "#2563EB",
    fontWeight: 600,
  },
  settingsSectionTitle: {
    fontSize: 15,
    fontWeight: 600,
    margin: "0 0 16px 0",
    color: "#111827",
  },
  toggleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 12px",
    border: "1px solid #E5E7EB",
    borderRadius: 6,
    fontSize: 13,
    cursor: "pointer",
  },
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    display: "flex",
    justifyContent: "flex-end",
    zIndex: 100,
  },
  drawer: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#FFFFFF",
    height: "100%",
    padding: 24,
    boxShadow: "-4px 0 15px rgba(0,0,0,0.1)",
    display: "flex",
    flexDirection: "column",
  },
  drawerHeader: {
    display: "flex",
    justifycontent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  closeBtn: {
    border: "none",
    background: "none",
    fontSize: 16,
    cursor: "pointer",
    color: "#6B7280",
  },
  formLabel: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "#374151",
  },
  formInput: {
    width: "100%",
    boxSizing: "border-box",
    padding: "8px 12px",
    border: "1px solid #D1D5DB",
    borderRadius: 6,
    fontSize: 13,
    outline: "none",
  },
  submitBtn: {
    flex: 1,
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 6,
    padding: "10px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  drawerCancelBtn: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    border: "1px solid #D1D5DB",
    color: "#374151",
    borderRadius: 6,
    padding: "10px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  },
  deptCard: {
    padding: 14,
    border: "1px solid #E5E7EB",
    borderRadius: 8,
    backgroundColor: "#FAFAFA",
  },
  deptCardTitle: {
    fontWeight: 600,
    fontSize: 14,
    color: "#111827",
  },
  deptCardSubtext: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 4,
  },
  levelCard: {
    padding: 16,
    border: "1px solid #E5E7EB",
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
  },
  levelCardCount: {
    fontSize: 20,
    fontWeight: 700,
    margin: "10px 0 2px 0",
  },
  levelCardSubtext: {
    fontSize: 12,
    color: "#6B7280",
  },
  reportText: {
    fontSize: 13,
    color: "#6B7280",
    marginBottom: 20,
  },
};

const dark = {
  ...light,
  appContainer: {
    ...light.appContainer,
    backgroundColor: "#242222",
    color: "#E5E7EB",
  },
  topHeader: {
    ...light.topHeader,
    backgroundColor: "#1E293B",
    borderBottom: "1px solid #334155",
  },
  pageTitle: {
    ...light.pageTitle,
    color: "#F1F5F9",
  },
  breadcrumbLink: {
    ...light.breadcrumbLink,
    color: "#60A5FA",
  },
  breadcrumbSeparator: {
    ...light.breadcrumbSeparator,
    color: "#64748B",
  },
  globalSearchBox: {
    ...light.globalSearchBox,
    backgroundColor: "#1E293B",
  },
  globalSearchInput: {
    ...light.globalSearchInput,
    color: "#E5E7EB",
  },
  shortcutKey: {
    ...light.shortcutKey,
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
    color: "#94A3B8",
  },
  userNameText: {
    ...light.userNameText,
    color: "#F1F5F9",
  },
  userRoleText: {
    ...light.userRoleText,
    color: "#94A3B8",
  },
  alertError: {
    ...light.alertError,
    backgroundColor: "#7F1D1D",
    color: "#FCA5A5",
    border: "1px solid #F87171",
  },
  statCard: {
    ...light.statCard,
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
  },
  statTitle: {
    ...light.statTitle,
    color: "#94A3B8",
  },
  statValue: {
    ...light.statValue,
    color: "#F1F5F9",
  },
  statSubtext: {
    ...light.statSubtext,
    color: "#64748B",
  },
  cardContainer: {
    ...light.cardContainer,
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
  },
  tableSearchBox: {
    ...light.tableSearchBox,
    backgroundColor: "#1E293B",
    border: "1px solid #334155",
  },
  tableSearchInput: {
    ...light.tableSearchInput,
    color: "#E5E7EB",
  },
  selectInput: {
    ...light.selectInput,
    backgroundColor: "#1E293B",
    color: "#E5E7EB",
    border: "1px solid #334155",
  },
  th: {
    ...light.th,
    color: "#94A3B8",
    borderBottom: "1px solid #334155",
  },
  tr: {
    ...light.tr,
    borderBottom: "1px solid #334155",
  },
  tableIndexText: {
    ...light.tableIndexText,
    color: "#94A3B8",
  },
  tableNameText: {
    ...light.tableNameText,
    color: "#F1F5F9",
  },
  tableBodyText: {
    ...light.tableBodyText,
    color: "#CBD5E1",
  },
  actionIconBtn: {
    ...light.actionIconBtn,
    border: "1px solid #334155",
  },
  cancelBtn: {
    ...light.cancelBtn,
    backgroundColor: "#334155",
    color: "#E5E7EB",
  },
  confirmText: {
    ...light.confirmText,
    color: "#F87171",
  },
  paginationRow: {
    ...light.paginationRow,
    borderTop: "1px solid #334155",
  },
  pageNumberBtn: {
    ...light.pageNumberBtn,
    backgroundColor: "#1E293B",
    color: "#E5E7EB",
    border: "1px solid #334155",
  },
  pageArrowBtn: {
    ...light.pageArrowBtn,
    backgroundColor: "#1E293B",
    color: "#94A3B8",
    border: "1px solid #334155",
  },
  emptyState: {
    ...light.emptyState,
    color: "#94A3B8",
  },
  settingsTabHeader: {
    ...light.settingsTabHeader,
    borderBottom: "1px solid #334155",
  },
  settingsTabBtn: {
    ...light.settingsTabBtn,
    color: "#94A3B8",
  },
  settingsTabBtnActive: {
    ...light.settingsTabBtnActive,
    backgroundColor: "#1E3A5F",
    color: "#60A5FA",
  },
  settingsSectionTitle: {
    ...light.settingsSectionTitle,
    color: "#F1F5F9",
  },
  toggleRow: {
    ...light.toggleRow,
    border: "1px solid #334155",
  },
  drawer: {
    ...light.drawer,
    backgroundColor: "#1E293B",
  },
  closeBtn: {
    ...light.closeBtn,
    color: "#94A3B8",
  },
  formLabel: {
    ...light.formLabel,
    color: "#E5E7EB",
  },
  formInput: {
    ...light.formInput,
    backgroundColor: "#1E293B",
    color: "#ffffff",
    border: "1px solid #334155",
  },
  drawerCancelBtn: {
    ...light.drawerCancelBtn,
    backgroundColor: "#1E293B",
    color: "#E5E7EB",
    border: "1px solid #334155",
  },
  deptCard: {
    ...light.deptCard,
    border: "1px solid #334155",
    backgroundColor: "#1E293B",
  },
  deptCardTitle: {
    ...light.deptCardTitle,
    color: "#F1F5F9",
  },
  deptCardSubtext: {
    ...light.deptCardSubtext,
    color: "#94A3B8",
  },
  levelCard: {
    ...light.levelCard,
    border: "1px solid #334155",
    backgroundColor: "#1E293B",
  },
  levelCardSubtext: {
    ...light.levelCardSubtext,
    color: "#94A3B8",
  },
  reportText: {
    ...light.reportText,
    color: "#94A3B8",
  },
};

export function getStyles(theme = "Light") {
  const isDark =
    theme === "Dark" ||
    (theme === "System Theme" &&
      typeof window !== "undefined" &&
      window.matchMedia &&
      window.matchMedia("(prefers-color-scheme: dark)").matches);
  return isDark ? dark : light;
}
